# Generated by Django 4.2.3 on 2023-08-13 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_post_poster_alter_userprofile_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.ManyToManyField(blank=True, null=True, related_name='comment_post', to='api.userprofile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_post', to='api.userprofile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='unlikes',
            field=models.ManyToManyField(blank=True, related_name='unliked_post', to='api.userprofile'),
        ),
    ]
