# Generated by Django 4.2.4 on 2023-08-18 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_post_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(default='https://img.freepik.com/icones-gratuites/utilisateur_318-159711.jpg', upload_to=''),
        ),
    ]
